---
title: "Ammonia Validation Workbook"
output: html_notebook
---

xxx

```{r, message=FALSE}
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyr)

```

xxx

```{r}
nh4.data.all <- read_excel("W:/lab/CHEMISTRY/Technical Support Projects/Project 202 - Validation of HACH Ammonia Method/1. Data/Processed Data/Ammonia by HACH Validation Workbook.xlsx", 
    sheet = "Raw Data")
```

Linearity was done at two levels: :Low & High

### Low Standard Curve ###

```{r}
nh4.low <- nh4.data.all %>%
  filter(Test == "Linearity" & Type == "Low")

low.fit <- lm(Reading~Level, data = nh4.low)
summary(low.fit)
confint(low.fit)
```

```{r}
low.plot <- ggplot(low.fit, aes(x=Level, y = Reading)) +
  geom_point(size=4, shape=21, col = "grey25", fill = "cornflowerblue") +
  geom_smooth(method=lm) +
  geom_abline(slope=1, intercept=0, lty=2, col="red") +
  labs(title = "Low Standard Curve", y = "Absorbance", x = "Ammonia, mg/L")+
  theme_bw() +
  theme(panel.grid.major = element_line(size = 0.5, color = "grey"), 
        axis.line = element_line(size = 0.7, color = "black"), 
        text = element_text(size = 14))

low.plot
```

### High Standard Curve ###

```{r}
nh4.high <- nh4.data.all %>%
  filter(Test == "Linearity" & Type == "High")

high.fit <- lm(Reading~Level, data = nh4.high)
summary(high.fit)
confint(high.fit)
```

```{r}
high.plot <- ggplot(high.fit, aes(x=Level, y = Reading)) +
  geom_point(size=4, shape=21, col = "grey25", fill = "cornflowerblue") +
  geom_smooth(method=lm) +
  geom_abline(slope=1, intercept=0, lty=2, col="red") +
  labs(title = "High Standard Curve", y = "Absorbance", x = "Ammonia, mg/L")+
  theme_bw() +
  theme(panel.grid.major = element_line(size = 0.5, color = "grey"), 
        axis.line = element_line(size = 0.7, color = "black"), 
        text = element_text(size = 14))

high.plot
```

### Low Level ANOVA ###

```{r}
low.aov.data <- nh4.data.all %>%
  filter(Test == "ANOVA" & Type == "Low")

low.aov <- aov(Reading~Batch, data=low.aov.data)
summary(low.aov)

```

```{r}
mean.sqr <- summary(low.aov)[1][[1]][[3]]
ncount <- as.numeric(length(low.aov$effects))/as.numeric(length(low.aov$coefficients))
sdr <- sqrt(mean.sqr[2])
interim <- sqrt((mean.sqr[1]-mean.sqr[2])/ncount)
sdR <- sqrt(sdr^2 + interim^2)
paste("Repeatability sd = ", round(sdr,3))
paste("Reproducibility sd = ",round(sdR,3))
```


